Describe how to run deployment playbooks
HSLdevcom/jore4-deploy pull request #1
Opened 2021-02-17 10:54 UTC by pallost

2021-02-17 11:13 UTC, lassemaatta requested changes

2021-02-17 11:13 UTC, lassemaatta commented on README.md
> +- Access to JORE4 Azure subscription
Tähän voisi kertoa, että mikä tämä on tai mistä tiedän onko minulla tuollainen access?

2021-02-17 11:13 UTC, lassemaatta commented on README.md
> +Run in Ansible shell:
Tässä jää vähän epäselväksi, että a) milloin minun pitäisi tämä komento ajaa (kun haluan opetella azurea? kun haluan päivittää tuotannon?) ja b) mitä siitä tapahtuu. Eli jos ajan tuon "playdev" komennon niin tuhoaako se azuresta meidän nykyisen infran ja asentaa kaiken uusiksi vai mitä oikein tapahtuu?

Mä mielelläni haluaisin nähdä jonkun "run this command to see what changes would occur in azure. By default no changes should be reported as you haven't yet modified the infrastructure configuration" tms. Eli vähän sama kuin mitä "terraform plan" tekee: 

> This command is a convenient way to check whether the execution plan for a set of changes matches your expectations without making any changes to real resources or to the state. For example, terraform plan might be run before committing a change to version control, to create confidence that it will behave as expected.

2021-02-17 11:13 UTC, lassemaatta commented on start-ansible-shell.sh
> +
Täällä vois ehkä jossain sanoa

    export COMPOSE_PROJECT_NAME=JORE4_INFRA

tjsp, jolloin nuo containerit yms olisi omassa nimiavaruudessaan

2021-02-17 11:13 UTC, lassemaatta commented on ansible/group_vars/all.yml
> +az_project_ca: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICynlDLuA8vTV1HZgA8Ot8EVqfL1i1Mo0IKoRVpCCSin tamaspallos@Tamass-MacBook-Pro.local" # Put your project's public CA here
Nämä taitavat olla jotain mitä löytyy vain sun tietokoneelta?

2021-02-17 12:25 UTC, pallost commented on README.md
> +- Access to JORE4 Azure subscription
Itse asiassa näitä scriptejä vois käyttää muuallakin :) Täsmennän tämä

2021-02-17 12:27 UTC, pallost commented on README.md
> +- Access to JORE4 Azure subscription
Mutta samalla sanoisin että jos haluat käyttää Azurea, sitten tiedät mikä on Azure subscription. Ei näiden scriptien scopeissa on opettaa käyttäjän mitenkin Azure toimii

2021-02-17 12:39 UTC, pallost commented on README.md
> +Run in Ansible shell:
Joo, lisäsin vähän tarkennusta tännekin... mutta meillä ei ole dry run optiota tässä kuin terraformissa on

2021-02-17 12:39 UTC, pallost commented on ansible/group_vars/all.yml
> +az_project_ca: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICynlDLuA8vTV1HZgA8Ot8EVqfL1i1Mo0IKoRVpCCSin tamaspallos@Tamass-MacBook-Pro.local" # Put your project's public CA here
jepp, hyvä löytö, poistan.

2021-02-17 12:43 UTC, pallost commented on start-ansible-shell.sh
> +
ok, lisäsin

2021-02-18 08:11 UTC, lassemaatta commented on README.md
> +This is an ideal script for testing if
Tämä lause näyttää jääneen kesken?

2021-02-18 09:24 UTC, pallost commented on README.md
> +This is an ideal script for testing if
jepp, tuli jotain huomiokatko, niin tämä lausekin jäi kesken :D poistan, ei ole tärkeä...

2021-02-18 09:25 UTC, pallost commented on README.md
> +Run in Ansible shell:
tiketti lisätty what-if scenariosta

2021-02-18 09:34 UTC, merged