Application db users
HSLdevcom/jore4-deploy pull request #30
Opened 2021-04-09 08:58 UTC by pallost

`playdev play-configure-db-users.yml`

- Will generate usernames and passwords and place them to `hsl-jore4-dev-vault` (`hasura-username`,
  `hasura-password`, `routeplanner-username`, `routeplanner-password`, etc.)
- Will set up a temporary SSH tunnel to the database
- Will connect to the database using db admin credentials from `hsl-jore4-dev-vault`. (That were
  generated with the database provisioning playbook)
- Will create database users for applications in the PostgreSQL database (`dbhasuradev`,
  `dbrouteplannerdev`, ...)
- Sets up permissions for these application users

2021-04-09 11:50 UTC, lassemaatta requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30)* status: 0 of 16 files reviewed, 3 unresolved discussions (waiting on @haphut, @jarkkoka, @jschummer, @pallost, and @tk-vincit)

___
*[ansible/files/create-db-and-users.sql, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MXqRJxdAGfv0xmeS_nV:-MXqRJxdAGfv0xmeS_nW:bw8zz3a) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/files/create-db-and-users.sql#L2)):*
> ```
> CREATE DATABASE :database_name;
> ```

What happens if we later want to add additional users? Should the creation of the database and adding new users even be in the same script/step?
___
*[ansible/files/create-db-and-users.sql, line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MXqRnoW6durkCwuQvas:-MXqRnoW6durkCwuQvat:b-d2gwka) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/files/create-db-and-users.sql#L11)):*
> ```TSQL
> GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO :hasura_username;
> GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO :hasura_username;
> ```

Is it a good idea to create N users in the same sql script or should we have a single "create-user.sql" script which is invoked multiple times (once per user)? 

I'm not sure if we need very fine-grained user-specific control on what privileges each user gets, instead we could maybe give the same kind of privileges for all users.. Or if we some day need e.g. a read-only user we could define a separate "create-readonly-user.sql" script for that.
___
*[ansible/roles/generate_password/tasks/main.yml, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MXqSs8RBhOYp2wtZSMh:-MXqSs8RBhOYp2wtZSMi:bhlfpu0) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/roles/generate_password/tasks/main.yml#L2)):*
> ```YAML
> ---
> # required input variables:
> ```

Perhaps this should be in the previous "Create database in Azure PostgreSQL" commit?


<!-- Sent from Reviewable.io -->

2021-04-09 13:11 UTC, pallost reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30)* status: 0 of 16 files reviewed, 3 unresolved discussions (waiting on @haphut, @jarkkoka, @jschummer, @lassemaatta, @pallost, and @tk-vincit)

___
*[ansible/files/create-db-and-users.sql, line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MXqRnoW6durkCwuQvas:-MXqkBbj6vtoD07wcWao:buqovo4) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/files/create-db-and-users.sql#L11)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

Is it a good idea to create N users in the same sql script or should we have a single "create-user.sql" script which is invoked multiple times (once per user)? 

I'm not sure if we need very fine-grained user-specific control on what privileges each user gets, instead we could maybe give the same kind of privileges for all users.. Or if we some day need e.g. a read-only user we could define a separate "create-readonly-user.sql" script for that.
</blockquote></details>

I know right now this is a copy-paste code, but my dream indeed is that we are setting fine-grained application-specific permissions - which would not be possible if we had a common create-user.sql
___
*[ansible/roles/generate_password/tasks/main.yml, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MXqSs8RBhOYp2wtZSMh:-MXqkSdd0JGdCWkk4yZC:b-cgsub8) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/roles/generate_password/tasks/main.yml#L2)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

Perhaps this should be in the previous "Create database in Azure PostgreSQL" commit?
</blockquote></details>

No, we do not need to generate a password when creating a database in a PostgreSQL instance


<!-- Sent from Reviewable.io -->

2021-04-12 08:57 UTC, pallost reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30)* status: 0 of 16 files reviewed, 3 unresolved discussions (waiting on @haphut, @jarkkoka, @jschummer, @lassemaatta, and @tk-vincit)

___
*[ansible/files/create-db-and-users.sql, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MXqRJxdAGfv0xmeS_nV:-MY4Hd3k3ahAIwCcjkSA:b-1s87q0) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/files/create-db-and-users.sql#L2)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

> ```
> CREATE DATABASE :database_name;
> ```

What happens if we later want to add additional users? Should the creation of the database and adding new users even be in the same script/step?
</blockquote></details>

I was wondering about this too, but I thought that this is a one-time configuration script that sets up the database and its users and we'd probably never touch or execute it again. Do you think it's necessary and important to cut these into two sql files and (presumably) two separate playbooks?


<!-- Sent from Reviewable.io -->

2021-04-13 06:33 UTC, lassemaatta requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30)* status: 0 of 16 files reviewed, 3 unresolved discussions (waiting on @haphut, @jarkkoka, @jschummer, @lassemaatta, @pallost, and @tk-vincit)

___
*[ansible/files/create-db-and-users.sql, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MXqRJxdAGfv0xmeS_nV:-MY8vZAJ4ZYtRXUTeUSl:b2e8hrr) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/files/create-db-and-users.sql#L2)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I was wondering about this too, but I thought that this is a one-time configuration script that sets up the database and its users and we'd probably never touch or execute it again. Do you think it's necessary and important to cut these into two sql files and (presumably) two separate playbooks?
</blockquote></details>

I think we may need at least a few additional backends for various APIs/integrations in the future: might make sense to split the "add user" part to a separate step.
___
*[ansible/files/create-db-and-users.sql, line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MXqRnoW6durkCwuQvas:-MY8viE75BxHZZAe8h0g:b57xals) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/files/create-db-and-users.sql#L11)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I know right now this is a copy-paste code, but my dream indeed is that we are setting fine-grained application-specific permissions - which would not be possible if we had a common create-user.sql
</blockquote></details>

Then I guess we need `create-hasura-user.sql`, `create-jore3-importer-user.sql` etc.


<!-- Sent from Reviewable.io -->

2021-04-13 11:58 UTC, jschummer requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30)* status: 0 of 16 files reviewed, 5 unresolved discussions (waiting on @haphut, @jarkkoka, @lassemaatta, @pallost, and @tk-vincit)

___
*[Dockerfile, line 1 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MY5D5nx-hFAQBBr3B8N:-MY5D5nx-hFAQBBr3B8O:b-itfqqr) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/Dockerfile#L1)):*
> ```Dockerfile
> FROM hsldevcom/azure-ansible:1.2.1
> ```

Would it be an option to have our own image (under hsldevcom or elsewhere)? Do you think we might add more own stuff later on?
___
*[ansible/files/create-db-and-users.sql, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MXqRJxdAGfv0xmeS_nV:-MY5CewVAEdfHVu617C0:bljywrj) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/files/create-db-and-users.sql#L2)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

I think we may need at least a few additional backends for various APIs/integrations in the future: might make sense to split the "add user" part to a separate step.
</blockquote></details>

I for my part would prefer if we could run the scripts again, or at least try to write them in such a way that they can be run again under some circumstances. If it's possible with reasonable effort, of course...
___
*[ansible/roles/create_keyvault_secret/tasks/main.yml, line 29 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MYA4Uum9sNU6be1k0Kt:-MYA4Uum9sNU6be1k0Ku:bdu16fo) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/roles/create_keyvault_secret/tasks/main.yml#L29)):*
> ```
>       set_fact:
>         "{{ output_name }}": "{{ secret.stdout }}"
> ```
This took me a while to understand, didn't know this was possible. Not bad :-D


<!-- Sent from Reviewable.io -->

2021-04-13 15:05 UTC, haphut requested changes
> Reviewed 3 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30)* status: 3 of 16 files reviewed, 10 unresolved discussions (waiting on @jarkkoka, @lassemaatta, @pallost, and @tk-vincit)

*[a discussion](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MYATK7IBZLNRTfFqqXT:-MYATK7IBZLNRTfFqqXU:b19ltun) (no related file):*
Thank you! Looks pretty, like your work in general. :grin: 

---
___
*[ansible/play-configure-db-and-users.yml, line 23 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MYAUjmcA2XvvQepsLH4:-MYAUjmcA2XvvQepsLH5:b-jurbbl) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/play-configure-db-and-users.yml#L23)):*
> ```YAML
>       username_secret_name: "{{ az_resource_group_name }}-hasura-username"
>       password_secret_name: "{{ az_resource_group_name }}-hasura-password"
>       username_output_name: "hasura_username"
> ```

As discussed in Slack, this is slightly unusual. I would also go for environment variables for non-secrets if possible. Or maybe a separate key vault for public information? Or at the very least a prefix for public information?
___
*[ansible/files/create-db-and-users.sql, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MXqRJxdAGfv0xmeS_nV:-MYAQ2uj-aOmTOezF31J:b21b7ku) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/files/create-db-and-users.sql#L2)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

I for my part would prefer if we could run the scripts again, or at least try to write them in such a way that they can be run again under some circumstances. If it's possible with reasonable effort, of course...
</blockquote></details>

As `IF NOT EXISTS` is not available for `CREATE DATABASE`, I agree with @lassemaatta and @jschummer . We'll likely need to modify the user privileges later on.
___
*[ansible/files/create-db-and-users.sql, line 4 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MYAXlup6UgjA06jt6FZ:-MYAXluq7CP-eAXMehzL:b4urdba) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/files/create-db-and-users.sql#L4)):*
> ```TSQL
> CREATE DATABASE :database_name;
> SELECT datname FROM pg_database;
> ```

This might be the place to turn on auditing with `pgaudit`. That might be a separate pull request and then we'd recreate the database from scratch.

Outline suggestion for that work:
- Separate user for auditing
- pgaudit in its own schema
- maybe prevent access to the pgaudit schema even from the SQL migrator, if possible
- `pgaudit.log = 'all';`
- Maybe `pgaudit.log_parameter = 'on';`
- Maybe `pgaudt.log_relation = 'on';`
- `pgaudit.role`
___
*[ansible/files/create-db-and-users.sql, line 8 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MYAh7MX8v7PDpR9UKJq:-MYAh7MX8v7PDpR9UKJr:b-u8l06x) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/files/create-db-and-users.sql#L8)):*
> ```TSQL
> CREATE USER :hasura_username WITH ENCRYPTED PASSWORD :'hasura_password';
> 
> REVOKE ALL PRIVILEGES ON DATABASE :database_name FROM :hasura_username;
> ```

I wonder if we can revoke everything in advance for all users before creating the users.
___
*[ansible/files/create-db-and-users.sql, line 9 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MYASgEw3az39gxu7Lh-:-MYASgEw3az39gxu7Lh0:b5c6xql) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/files/create-db-and-users.sql#L9)):*
> ```TSQL
> 
> REVOKE ALL PRIVILEGES ON DATABASE :database_name FROM :hasura_username;
> GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO :hasura_username;
> ```

Whoever runs the SQL schema changes needs to be able to create new schemas for the database. If we wish to avoid juggling between this ansible method and the Kubernetes method of changing the database "configuration", that migrator also needs to grant rights to the other users for those schemas. We do not know the schemas early on in the project and need the flexibility to change them later as well.

Currently that migrator is Hasura.

So `GRANT CREATE ON DATABASE :database_name TO :hasura_username WITH GRANT OPTION;` I *think* `WITH GRANT OPTION` is required but one could check whether one can grant access to schemas with hasura without it.

Having the usernames as secrets in the key vault is problematic if we wish to grant access to those schemas from the migrator, though. Hmm...
___
*[ansible/files/create-db-and-users.sql, line 10 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MYAjRqUEEBhYAuxRbCG:-MYAjRqUEEBhYAuxRbCH:b-4wjfli) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/files/create-db-and-users.sql#L10)):*
> ```TSQL
> REVOKE ALL PRIVILEGES ON DATABASE :database_name FROM :hasura_username;
> GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO :hasura_username;
> GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO :hasura_username;
> ```

Also, I thought we would drop the `public` schema in the SQL migration scripts so these grants would not be useful.
___
*[ansible/files/create-db-and-users.sql, line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MXqRnoW6durkCwuQvas:-MYAQDXh7RsRQ0knqVpI:b-1ik5k1) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/files/create-db-and-users.sql#L11)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

Then I guess we need `create-hasura-user.sql`, `create-jore3-importer-user.sql` etc.
</blockquote></details>

Many tools use one transaction per SQL file. It makes sense to me to have a single transaction after which the database is ready for Kubernetes.

That might not matter much as we currently use no automation to sync the creation of the database with the use of the database and might not need that at any point.

(With this comment I'm also testing whether Reviewable will override Lasse's disposition with mine. I hope not.)
___
*[ansible/roles/execute_psql_file/tasks/main.yml, line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MYAjGn3Dol-eB23sThx:-MYAjGn3Dol-eB23sThy:bdzzoi1) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/roles/execute_psql_file/tasks/main.yml#L11)):*
> ```YAML
> # optional input variables:
> # - psql_extra_params: list of extra command line params that are used, e.g. ["-v date_param='2020-01-01'"]
> ```

Is this usable here instead: https://docs.ansible.com/ansible/latest/collections/community/postgresql/index.html ?


<!-- Sent from Reviewable.io -->

2021-04-14 11:13 UTC, lassemaatta approved these changes
Looks fine to me, perhaps @jschummer and @haphut should also verify.

> Reviewed 1 of 17 files at r2, 1 of 2 files at r3, 3 of 4 files at r4, 2 of 2 files at r5, 8 of 9 files at r6, 6 of 6 files at r7.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-:-MYF4AU49oFzCIJ-t_JA:btpoa6f)* status: 21 of 23 files reviewed, 10 unresolved discussions (waiting on @jarkkoka, @lassemaatta, @pallost, and @tk-vincit)



<!-- Sent from Reviewable.io -->

2021-04-14 12:30 UTC, pallost reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30)* status: 21 of 23 files reviewed, 10 unresolved discussions (waiting on @haphut, @jarkkoka, @jschummer, @lassemaatta, and @tk-vincit)

*[a discussion](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MYATK7IBZLNRTfFqqXT:-MYFIEBp6jaYs_khggC-:bvtk9y9) (no related file):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

Thank you! Looks pretty, like your work in general. :grin: 
</blockquote></details>

Thanks :)

---
___
*[Dockerfile, line 1 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MY5D5nx-hFAQBBr3B8N:-MYFIJXJE6XqBpjzLXiF:b-ca7fvn) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/Dockerfile#L1)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Would it be an option to have our own image (under hsldevcom or elsewhere)? Do you think we might add more own stuff later on?
</blockquote></details>

We might add more own stuff, but so far I did not see any need to publish this minor change as our own image. Do you see a use-case for that?
___
*[ansible/play-configure-db-and-users.yml, line 23 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MYAUjmcA2XvvQepsLH4:-MYFI_LpEbVHz0-5YguB:b67m0nd) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/play-configure-db-and-users.yml#L23)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

As discussed in Slack, this is slightly unusual. I would also go for environment variables for non-secrets if possible. Or maybe a separate key vault for public information? Or at the very least a prefix for public information?
</blockquote></details>

why I suggest this to be stored in a key-vault (or other Azure configuration store) is because ansible knows this information but kubernetes does not. A key-vault enables transition of information between these two layers. Technically, we could also probably use something like the Azure App Configuration store, but that would require additional hassle to map those configurations to Kubernetes. I don't really know whether having a separate key-vault for public configuration data or a public prefix would give an additional benefit, maybe it would work. 

But personally I just don't see why we couldn't just set all public and private configuration values from the same place, the key-vault. Why is it necessary to have public configuration information separated...?
___
*[ansible/files/create-db-and-users.sql, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MXqRJxdAGfv0xmeS_nV:-MYFJfqRB_QZq8ds07Mt:b-yyd4t4) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/files/create-db-and-users.sql#L2)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

As `IF NOT EXISTS` is not available for `CREATE DATABASE`, I agree with @lassemaatta and @jschummer . We'll likely need to modify the user privileges later on.
</blockquote></details>

these playbooks and sql scripts have been run multiple times and they work as intended. Create db/users if they don't exist and update when rerun. This is also why it has the "REVOKE" line in the user creation part
___
*[ansible/files/create-db-and-users.sql, line 4 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MYAXlup6UgjA06jt6FZ:-MYFL0ciDgD2VIMrDNn6:bczrymh) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/files/create-db-and-users.sql#L4)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

This might be the place to turn on auditing with `pgaudit`. That might be a separate pull request and then we'd recreate the database from scratch.

Outline suggestion for that work:
- Separate user for auditing
- pgaudit in its own schema
- maybe prevent access to the pgaudit schema even from the SQL migrator, if possible
- `pgaudit.log = 'all';`
- Maybe `pgaudit.log_parameter = 'on';`
- Maybe `pgaudt.log_relation = 'on';`
- `pgaudit.role`
</blockquote></details>

pgaudit is new for me... :) could you create a follow-up issue about this to the Kanban board? This is already a pretty huge PR that I wouldn't want to bloat anymore... Thanks!
___
*[ansible/files/create-db-and-users.sql, line 8 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MYAh7MX8v7PDpR9UKJq:-MYFLDjh3bxXI8GvWIqT:b-35bup6) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/files/create-db-and-users.sql#L8)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

I wonder if we can revoke everything in advance for all users before creating the users.
</blockquote></details>

that's what that REVOKE line does, or did you have something else in mind?
___
*[ansible/files/create-db-and-users.sql, line 9 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MYASgEw3az39gxu7Lh-:-MYFKQm6DaaAh6UgJO26:b-wrq1lq) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/files/create-db-and-users.sql#L9)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

Whoever runs the SQL schema changes needs to be able to create new schemas for the database. If we wish to avoid juggling between this ansible method and the Kubernetes method of changing the database "configuration", that migrator also needs to grant rights to the other users for those schemas. We do not know the schemas early on in the project and need the flexibility to change them later as well.

Currently that migrator is Hasura.

So `GRANT CREATE ON DATABASE :database_name TO :hasura_username WITH GRANT OPTION;` I *think* `WITH GRANT OPTION` is required but one could check whether one can grant access to schemas with hasura without it.

Having the usernames as secrets in the key vault is problematic if we wish to grant access to those schemas from the migrator, though. Hmm...

</blockquote></details>

I see clear separation or roles: this script only sets up users and their permissions. Hasura then can set up all the database schemas it wants. It's not in the scope of this PR to figure out how to create database schema migrations, that's some future task to think about. I also don't think that ansible should do any more database operations than this
___
*[ansible/files/create-db-and-users.sql, line 10 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MYAjRqUEEBhYAuxRbCG:-MYFLOmK9-2q-0BeS-7P:biiv42e) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/files/create-db-and-users.sql#L10)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

Also, I thought we would drop the `public` schema in the SQL migration scripts so these grants would not be useful.
</blockquote></details>

TBH, this PR does not intend to have a 100% ready set up for all the database and db user stuff, this just shows an example how to do stuff like this. I'd prefer to iterate on this and not bloat this PR anymore. Could you please create a follow-up issue about this to the Kanban board? Thanks!
___
*[ansible/files/create-db-and-users.sql, line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MXqRnoW6durkCwuQvas:-MYFK5kK46_2k9F4sH80:b-fudacy) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/files/create-db-and-users.sql#L11)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

Many tools use one transaction per SQL file. It makes sense to me to have a single transaction after which the database is ready for Kubernetes.

That might not matter much as we currently use no automation to sync the creation of the database with the use of the data [...]

2021-04-15 06:02 UTC, lassemaatta reviewed
> Reviewed 16 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30)* status: all files reviewed, 11 unresolved discussions (waiting on @haphut, @jarkkoka, @jschummer, @lassemaatta, @pallost, and @tk-vincit)

___
*[README.md, line 806 at r7](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MYJ6OQj6nAZV3yYpMIW:-MYJ6OQj6nAZV3yYpMIX:bxdv8ny) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/0faa083a3f43d669f8f05314a52a058099837bfe/README.md#L806)):*
> ```Markdown
> - `jore4dev` database is created within the database instance
> 
> `playdev play-configure-db-users.yml`
> ```

Just verifying: If I need to add a new user, I need to 

1. Add:

```
- name: "Create db user for foobar {{ az_environment }}"
  hosts: localhost
  roles:
    - role: create_db_user
      keyvault_name: "{{ az_resource_group_name }}-vault"
      db_user_name: foobar_user
      # db_admin_username: (passed down directly)
      # db_admin_password: (passed down directly)
      db_hostname: localhost
      db_port: 1234
      # database_name: (passed down directly)
```

2. Run `playdev play-configure-db-users.yml`

=> The only effect is that the new user is create (and old users are not modified)?

 


<!-- Sent from Reviewable.io -->

2021-04-15 06:22 UTC, jschummer requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30)* status: all files reviewed, 10 unresolved discussions (waiting on @haphut, @jarkkoka, @lassemaatta, @pallost, and @tk-vincit)

___
*[Dockerfile, line 1 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MY5D5nx-hFAQBBr3B8N:-MYJ7zGiC5HzMdv6gmSc:bshhxgp) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/Dockerfile#L1)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

We might add more own stuff, but so far I did not see any need to publish this minor change as our own image. Do you see a use-case for that?
</blockquote></details>

Not sure if I want to build the image once an hour (when the azure auth expires), but I think we can come back to that in another PR. So let's leave it like this for now :+1: 
___
*[ansible/play-configure-db-and-users.yml, line 23 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MYAUjmcA2XvvQepsLH4:-MYJ8YNk2XyNVqKe4Abu:b-ivcokl) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/play-configure-db-and-users.yml#L23)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

why I suggest this to be stored in a key-vault (or other Azure configuration store) is because ansible knows this information but kubernetes does not. A key-vault enables transition of information between these two layers. Technically, we could also probably use something like the Azure App Configuration store, but that would require additional hassle to map those configurations to Kubernetes. I don't really know whether having a separate key-vault for public configuration data or a public prefix would give an additional benefit, maybe it would work. 

But personally I just don't see why we couldn't just set all public and private configuration values from the same place, the key-vault. Why is it necessary to have public configuration information separated...?
</blockquote></details>

I for myself don't like the key-vault solution because it is cumbersome to use and you can't see many values at the same time (unless we write a script or similar). Also I think there's truth in what haphut says, that after a while people won't remember what is really secret and what is public (and just in the vault for convenience).

But like mentioned in slack before, I don't know any good solution which would be as easy to use. So in that sense the public prefix (or own vault) may be good because it tackles one of the issues.
___
*[ansible/roles/execute_psql_file/tasks/main.yml, line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MYAjGn3Dol-eB23sThx:-MYJA0zvDL2TTqm8WLfk:b-o7ycs4) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/roles/execute_psql_file/tasks/main.yml#L11)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

probably is, but that would require additional changes to the azure-ansible docker image that I wanted to avoid
</blockquote></details>

I think there might be benefits in using that plugin, but on the other hand I'm hoping that we won't be running lots of sql in these ansible scripts, maybe not ever more that what this PR does. In that sense it might not be worth the trouble.


<!-- Sent from Reviewable.io -->

2021-04-15 08:09 UTC, pallost reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30)* status: all files reviewed, 10 unresolved discussions (waiting on @haphut, @jarkkoka, @jschummer, @lassemaatta, and @tk-vincit)

___
*[Dockerfile, line 1 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MY5D5nx-hFAQBBr3B8N:-MYJYmQB-Onybw3KgzmQ:b-1vaf3u) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/Dockerfile#L1)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Not sure if I want to build the image once an hour (when the azure auth expires), but I think we can come back to that in another PR. So let's leave it like this for now :+1: 
</blockquote></details>

the docker build gets cached, so you don't make changes to the image, you only need to build it once
___
*[README.md, line 806 at r7](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MYJ6OQj6nAZV3yYpMIW:-MYJYzT69h3wNzEIKl1M:b90bsnx) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/0faa083a3f43d669f8f05314a52a058099837bfe/README.md#L806)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

Just verifying: If I need to add a new user, I need to 

1. Add:

```
- name: "Create db user for foobar {{ az_environment }}"
  hosts: localhost
  roles:
    - role: create_db_user
      keyvault_name: "{{ az_resource_group_name }}-vault"
      db_user_name: foobar_user
      # db_admin_username: (passed down directly)
      # db_admin_password: (passed down directly)
      db_hostname: localhost
      db_port: 1234
      # database_name: (passed down directly)
```

2. Run `playdev play-configure-db-users.yml`

=> The only effect is that the new user is create (and old users are not modified)?

 
</blockquote></details>

also the script for the old users are run but as their sql script is not modified, the same create-revoke-grant rounds will be run and the old users will be left as is. Is that okay?
___
*[ansible/play-configure-db-and-users.yml, line 23 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MYAUjmcA2XvvQepsLH4:-MYJZImPBMVkHEeGGqbU:b8r3h3e) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/play-configure-db-and-users.yml#L23)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

I for myself don't like the key-vault solution because it is cumbersome to use and you can't see many values at the same time (unless we write a script or similar). Also I think there's truth in what haphut says, that after a while people won't remember what is really secret and what is public (and just in the vault for convenience).

But like mentioned in slack before, I don't know any good solution which would be as easy to use. So in that sense the public prefix (or own vault) may be good because it tackles one of the issues.
</blockquote></details>

well, let's take the "public" prefix into use as everybody seems to want some kind of separation. It's true that viewing/editing multiple secrets at once is cumbersome, we'll have to figure out a solution for that if it happens often.
___
*[ansible/roles/execute_psql_file/tasks/main.yml, line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MYAjGn3Dol-eB23sThx:-MYJZttd0G5-PpV6vFQC:boc7q50) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/roles/execute_psql_file/tasks/main.yml#L11)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

I think there might be benefits in using that plugin, but on the other hand I'm hoping that we won't be running lots of sql in these ansible scripts, maybe not ever more that what this PR does. In that sense it might not be worth the trouble.
</blockquote></details>

If you see fit to use that plugin, let's put it as an "idea" to the kanban board!
___
*[ansible/roles/generate_password/tasks/main.yml, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MXqSs8RBhOYp2wtZSMh:-MYJ_1Dr75cVAeMvdvau:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/roles/generate_password/tasks/main.yml#L2)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

No, we do not need to generate a password when creating a database in a PostgreSQL instance
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-15 10:20 UTC, lassemaatta approved these changes
> Reviewed 9 of 9 files at r8.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30)* status: all files reviewed, 9 unresolved discussions (waiting on @haphut, @jarkkoka, @jschummer, @lassemaatta, @pallost, and @tk-vincit)

___
*[README.md, line 806 at r7](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MYJ6OQj6nAZV3yYpMIW:-MYK1T3z4TBhfYvYDUxD:b-cvte6u) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/0faa083a3f43d669f8f05314a52a058099837bfe/README.md#L806)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

also the script for the old users are run but as their sql script is not modified, the same create-revoke-grant rounds will be run and the old users will be left as is. Is that okay?
</blockquote></details>

I guess that's ok.


<!-- Sent from Reviewable.io -->

2021-04-15 13:23 UTC, jschummer approved these changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30)* status: all files reviewed, 8 unresolved discussions (waiting on @haphut, @jarkkoka, @lassemaatta, @pallost, and @tk-vincit)

___
*[Dockerfile, line 1 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MY5D5nx-hFAQBBr3B8N:-MYKfYL6BYluvKw9V0iy:bxrijg6) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/Dockerfile#L1)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

the docker build gets cached, so you don't make changes to the image, you only need to build it once
</blockquote></details>

Ok, I didn't know docker-compose's build functionality was that clever :+1: 
___
*[ansible/roles/execute_psql_file/tasks/main.yml, line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MYAjGn3Dol-eB23sThx:-MYKg3l594i2hTLd_NPJ:b-1825p8) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/roles/execute_psql_file/tasks/main.yml#L11)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

If you see fit to use that plugin, let's put it as an "idea" to the kanban board!
</blockquote></details>

I actually vote for just keeping it in mind. But if one day we'll run more SQL from ansible, it might be a good idea.


<!-- Sent from Reviewable.io -->

2021-04-15 15:12 UTC, haphut approved these changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30)* status: all files reviewed, 6 unresolved discussions (waiting on @haphut, @jarkkoka, @lassemaatta, @pallost, and @tk-vincit)

___
*[ansible/files/create-db-and-users.sql, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MXqRJxdAGfv0xmeS_nV:-MYL3f7O5-6BxhCJzfxj:bf199js) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/files/create-db-and-users.sql#L2)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

these playbooks and sql scripts have been run multiple times and they work as intended. Create db/users if they don't exist and update when rerun. This is also why it has the "REVOKE" line in the user creation part
</blockquote></details>

I'm surprised if this idempotent. I get an error when I run locally:
```plpgsql
BEGIN;
  CREATE ROLE foo;
COMMIT;
BEGIN;
  CREATE ROLE foo;
COMMIT;
```

The error message is:
```
2021-04-15 15:04:30.627 UTC [73] ERROR:  role "foo" already exists
2021-04-15 15:04:30.627 UTC [73] STATEMENT:  CREATE ROLE foo;
```

Here's one way to handle existing users: https://stackoverflow.com/a/55954480
___
*[ansible/files/create-db-and-users.sql, line 4 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MYAXlup6UgjA06jt6FZ:-MYKfdnX0UWKGKQ96MWT:b-fbae0c) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/files/create-db-and-users.sql#L4)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

pgaudit is new for me... :) could you create a follow-up issue about this to the Kanban board? This is already a pretty huge PR that I wouldn't want to bloat anymore... Thanks!
</blockquote></details>

Makes sense. Done: https://github.com/HSLdevcom/jore4/issues/299
___
*[ansible/files/create-db-and-users.sql, line 8 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MYAh7MX8v7PDpR9UKJq:-MYKd3A0-VpZpBeA-f4I:b-qlilx4) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/files/create-db-and-users.sql#L8)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

that's what that REVOKE line does, or did you have something else in mind?
</blockquote></details>

I meant that there might be a way to disallow everything by default even before creating users. I did not research concrete solutions. I don't think it's necessary to do here. It would just be just one line less to remember to write for each user.
___
*[ansible/files/create-db-and-users.sql, line 9 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MYASgEw3az39gxu7Lh-:-MYKay03-Y4dYZ78rAeQ:ba4c09w) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/files/create-db-and-users.sql#L9)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I see clear separation or roles: this script only sets up users and their permissions. Hasura then can set up all the database schemas it wants. It's not in the scope of this PR to figure out how to create database schema migrations, that's some future task to think about. I also don't think that ansible should do any more database operations than this
</blockquote></details>

In principle I agree with the responsibilities you suggested. I do not mean to handle SQL schema migrations here. Who will grant permissions for the other PG users to the schemas created by the SQL schema migrator?

If Ansible grants permissions, we have an implicit order in which things need to happen: 1) create schemas with migrator, 2) grant permissions with Ansible, 3) use schemas in components.

If migrator grants permissions, migrator has to have the ability to grant permissions on arbitrary schemas (and to read the usernames from Kubernetes secrets).

Maybe I'm misunderstanding something and this is not a problem. I'm fine with iterating on this later but would like to hear what you think of this.
___
*[ansible/files/create-db-and-users.sql, line 10 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MYAjRqUEEBhYAuxRbCG:-MYL1GVy7CVRmH5Porsd:b6i142m) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8944c8407de13ac27aadc6a4da55b3918398675e/ansible/files/create-db-and-users.sql#L10)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

TBH, this PR does not intend to have a 100% ready set up for all the database and db user stuff, this just shows an example how to do stuff like this. I'd prefer to iterate on this and not bloat this PR anymore. Could you please create a follow-up issue about this to the Kanban board? Thanks!
</blockquote></details>

That's fine. It's not very important now.


<!-- Sent from Reviewable.io -->

2021-04-16 11:23 UTC, lassemaatta requested changes
> Reviewed 1 of 22 files at r9, 2 of 4 files at r10, 1 of 12 files at r11, 4 of 10 files at r12, 3 of 4 files at r14, 2 of 2 files at r15, 11 of 12 files at r16, 4 of 4 files at r17.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30)* status: 25 of 28 files reviewed, 6 unresolved discussions (waiting on @haphut, @jarkkoka, @lassemaatta, @pallost, and @tk-vincit)

___
*[README.md, line 802 at r17](https://reviewable.io/reviews/hsldevcom/jore4-deploy/30#-MYPPcfA1FMnzKC-jDL2:-MYPPcfA1FMnzKC-jDL3:blhkop7) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/5382d5a539b25862a7fd50a301f7464d29edb7a0/README.md#L802)):*
> ```Markdown
> - Will connect to the `postgres` database within the instance using db admin credentials
>   from `hsl-jore4-dev-vault`. (That were generated with the database provisioning playbook)
> - Will create the `jore4dev` database in PostgreSQL
> ```

As I mentioned in slack, I don't think this should be called _configure_ as this destroys stuff(?).


<!-- Sent from Reviewable.io -->

2021-04-19 05:47 UTC, merged