Add support for provisioning and configuring a bastion host
HSLdevcom/jore4-deploy pull request #7
Opened 2021-03-02 18:26 UTC by jschummer

...based on the scripts provided in the HSL server-based repo:
https://gitlab.hsl.fi/platforms/server-based

Developers can log into the host using a public key, which has been
signed using the shared developer private key (stored in the common
Azure key vault).

Instructions for signing your own key as a developer in order to log
into the bastion host can be found here:
https://gitlab.hsl.fi/developer-resources/azure-ansible/-/tree/master#signing-users-public-key-with-private-ca-key

The CA key is stored in the hsl-jore4-vault, which is common to all
environments.

2021-03-03 07:40 UTC, pallost commented on README.md
> +bastion host.
Tästä README:stä kaipaan vielä:
- linkki server-based/aks-based repolle että se oli meidän lähde
- ohjeista että tarvittaessa miten voimme päivittää CA avaimen bastion hostissa. Ja että tämä tarkoittaa että kaikki käyttäjä ssh avaimet myös täytyy päivittää
- ohjeista että millaisia resursseja tämä luo, mihin resource groupiin (bastion host, IP osoite, jne)
- ohjeista että mitä subnettia tämä käyttää, mikä portti ja IP avaruus on sallittu
- ohjeista että miten generoidaan sopiva ssh avain (ladataan hsl-jore4-vaultista avain käsin, korjataan rivinvaihdot, generoidaan oma ssh avain miten, poistetaan omasta koneesta CA avain)
- ohjeista että miten yhdistetään bastion hostiin (IP rajoitettu, niin Vincit VPN päälle. Muuten täytyy lisätä oma IP osoite env-*.ymleihin. Komennot että miten päästään sisään `ssh -i ~/.ssh/jore4-key hsladmin@bastion.IP`)
- ohjeista että miten tehdään tunneli esm jore3 kantaan (`ssh -i ~/.ssh/jore4-key -L port:mssqlIP:port hsladmin@bastion.IP`)
- troubleshooting ohjeista (invalid key -> CA avain rivinvaihdot. Permission denied -> onko ssh -i parametri oikea. jne)

2021-03-03 07:41 UTC, pallost commented on README.md
> +### 4. Provisioning a bastion host and configuring it
sun pitäisi päivittää table of contentsin (`npx doctoc README.md`)

2021-03-03 07:42 UTC, pallost commented on README.md
> +bastion host.
ohjeista että automaattisesti generoitu `ansible_initial_key` käytetään kun ensin päästään bastion hostiin, mutta sitten tämä on heitetty pois ja vaihdettu CA avaimeen

2021-03-03 07:45 UTC, pallost requested changes
readme kaipaisi vähän rakkausta, muuten näyttää hyvältä

2021-03-05 08:26 UTC, pallost commented on ansible/roles/azure_bastion_host/tasks/main.yml
> +    tags:
kannattaa myös tägata erikseen niin että `requiredUptime: 'office hours'`

2021-03-09 09:37 UTC, jschummer commented on README.md
> +bastion host.
Tehty ehdotetut toimenpiteet, paitsi:
- mikä portti ja IP avaruus on sallittu
  => Tämä playbook ei koske näihin / huomioi niitä, vaan taitavat `play-provision-rg-and-nets.yml`-playbookin määrittelemiä

- ohjeista että miten generoidaan sopiva ssh avain (ladataan hsl-jore4-vaultista avain käsin, korjataan rivinvaihdot, generoidaan oma ssh avain miten, poistetaan omasta koneesta CA avain)
- ohjeista että miten yhdistetään bastion hostiin (IP rajoitettu, niin Vincit VPN päälle. Muuten täytyy lisätä oma IP osoite env-*.ymleihin. Komennot että miten päästään sisään ssh -i ~/.ssh/jore4-key hsladmin@bastion.IP)
- ohjeista että miten tehdään tunneli esm jore3 kantaan (ssh -i ~/.ssh/jore4-key -L port:mssqlIP:port hsladmin@bastion.IP)
troubleshooting ohjeista (invalid key -> CA avain rivinvaihdot. Permission denied -> onko ssh -i parametri oikea. jne)
  => Nämä eivät mielestäni kuulu tähän, koska ne eivät ole spesiifisiä tälle playbookille. Sen sijaan olin lisännyt ohjeet tänne: https://github.com/HSLdevcom/jore4/blob/main/wiki/jore3.md

2021-03-09 09:37 UTC, jschummer commented on README.md
> +### 4. Provisioning a bastion host and configuring it
done

2021-03-09 11:53 UTC, pallost requested changes
> Reviewed 2 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/7)* status: 2 of 10 files reviewed, 2 unresolved discussions (waiting on @jschummer)

___
*[README.md, line 149 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/7#-MVLn0AW5zJTv_Zjd3Qg:-MVLn0AX-KbixZwM7ejL:bh1gtfd) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/e415f25559e40bf1f010ecf8ad20d0822bf09f80/README.md#L149)):*
> ```Markdown
> See https://docs.microsoft.com/en-us/azure/security-center/security-center-enable-data-collection
> 
> ### 4. Provisioning a bastion host and configuring it
> ```

Table of Contents ei taida olla päivitettyä edelleenkään...
`npx doctoc README.md`
___
*[ansible/play-provision-bastion-host.yml, line 6 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/7#-MVLnh7u4A1a_5pTua0Y:-MVLnh7u4A1a_5pTua0Z:b8yg8t6) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/e415f25559e40bf1f010ecf8ad20d0822bf09f80/ansible/play-provision-bastion-host.yml#L6)):*
> ```YAML
>   connection: local
>   gather_facts: false
> ```

Kun sulla on monta askeleita tässä playbookissa, olisi varmaan selkeämpi jos poistaisit extra rivinvaihdot kaikki "roles" otsikon edestä, niin näkyy paremmin että mihin blockiin ne kuuluvat


<!-- Sent from Reviewable.io -->

2021-03-09 12:16 UTC, pallost requested changes
> Reviewed 7 of 10 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/7)* status: 9 of 10 files reviewed, 4 unresolved discussions (waiting on @jschummer)

___
*[README.md, line 171 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/7#-MVLt1Vy8Q1I26mGNCu8:-MVLt1Vy8Q1I26mGNCu9:br58ar6) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/6d5bdd80594e5b04fa5cc5040dcda72d93778937/README.md#L171)):*
> ```Markdown
> host in the files
> - /etc/ssh/ca.pub and
> - /home/hsladmin/.ssh/authorized_keys
> ```

I am missing at least a link to the instructions how to generate own SSH key based on the CA key (in the wiki)
___
*[ansible/templates/bastionhost.arm.json, line 77 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/7#-MVLuGSDE2ujh4RBkMOH:-MVLuGSDE2ujh4RBkMOI:b4yjkfm) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/6d5bdd80594e5b04fa5cc5040dcda72d93778937/ansible/templates/bastionhost.arm.json#L77)):*
> ```JSON
>                 "description": "The name of the public network interface."
>             },
>             "defaultValue": "[concat(parameters('vmName'), '-management-nic')]"
> ```

as the public subnet's name has been "subnet-public", maybe it would be clearer if this was also named "-public-nic"
___
*[ansible/templates/bastionhost.arm.json, line 196 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/7#-MVLtkdu52o8J2Rgg7Cu:-MVLtkdv7Cxs_0YMgkDx:b-jztxvn) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/6d5bdd80594e5b04fa5cc5040dcda72d93778937/ansible/templates/bastionhost.arm.json#L196)):*
> ```JSON
>             ],
>             "tags": {
>                 "requiredUptime": "office hours"
> ```

did this work? :)


<!-- Sent from Reviewable.io -->

2021-03-09 14:58 UTC, jschummer reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/7)* status: 9 of 10 files reviewed, 5 unresolved discussions (waiting on @pallost)

*[a discussion](https://reviewable.io/reviews/hsldevcom/jore4-deploy/7#-MVMU0br57jiF2NmDqoG:-MVMU0bsCn-nXNymeSV6:b-3pv2qa) (no related file):*
Tein ehdotetut muutokset ja pari muutakin.

Mm. poistin taas sen "-All resources are created in the 'dev' environment as per the configuration used by the `playdev`-alias." -lauseen README.md:stä, koska huomasin, että asia on selitetty jo ylempänä.

---
___
*[README.md, line 149 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/7#-MVLn0AW5zJTv_Zjd3Qg:-MVM7_k_CodE-qQcfH4E:bwgpku) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/e415f25559e40bf1f010ecf8ad20d0822bf09f80/README.md#L149)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Table of Contents ei taida olla päivitettyä edelleenkään...
`npx doctoc README.md`

</blockquote></details>

On päivitetty jo. Taisi mennä jo edellisessä versiossa, sen takia ei näy tässä enää.
___
*[README.md, line 171 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/7#-MVLt1Vy8Q1I26mGNCu8:-MVM9YSQ7d0BPl3lV-2s:b-dbqujw) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/6d5bdd80594e5b04fa5cc5040dcda72d93778937/README.md#L171)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I am missing at least a link to the instructions how to generate own SSH key based on the CA key (in the wiki)
</blockquote></details>

Taisi unohtua, kopsasin nyt tämän commitin commit-viestistä sinne jore3.md:hen.
___
*[ansible/play-provision-bastion-host.yml, line 6 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/7#-MVLnh7u4A1a_5pTua0Y:-MVME0tg1Xh4_ky6AJq5:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/e415f25559e40bf1f010ecf8ad20d0822bf09f80/ansible/play-provision-bastion-host.yml#L6)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Kun sulla on monta askeleita tässä playbookissa, olisi varmaan selkeämpi jos poistaisit extra rivinvaihdot kaikki "roles" otsikon edestä, niin näkyy paremmin että mihin blockiin ne kuuluvat
</blockquote></details>

Done.
___
*[ansible/templates/bastionhost.arm.json, line 77 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/7#-MVLuGSDE2ujh4RBkMOH:-MVMLLDV1A5hYIByhiDe:bpnz34p) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/6d5bdd80594e5b04fa5cc5040dcda72d93778937/ansible/templates/bastionhost.arm.json#L77)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

as the public subnet's name has been "subnet-public", maybe it would be clearer if this was also named "-public-nic"
</blockquote></details>

Tämä oli siis suoraan HSL:n bastion host templatesta otettu, mutta voi olla hyvä tarkennus tuo "public". Vaihdoin siis.
___
*[ansible/templates/bastionhost.arm.json, line 196 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/7#-MVLtkdu52o8J2Rgg7Cu:-MVMSa_JCZ2sSQJyVfJG:bmq7uuk) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/6d5bdd80594e5b04fa5cc5040dcda72d93778937/ansible/templates/bastionhost.arm.json#L196)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

did this work? :)
</blockquote></details>

En ihan ymmärrä. Miksi ei olisi toiminut?

Vaihdoin tämän nyt itse asiassa niin, että se käyttää az_requireduptime_tag_default-muuttujaa.


<!-- Sent from Reviewable.io -->

2021-03-10 10:09 UTC, pallost requested changes
> Reviewed 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/7)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @jschummer)

___
*[README.md, line 171 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/7#-MVLt1Vy8Q1I26mGNCu8:-MVQ_wr5CNhZf571Q1zG:b-mvjbqn) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/6d5bdd80594e5b04fa5cc5040dcda72d93778937/README.md#L171)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Taisi unohtua, kopsasin nyt tämän commitin commit-viestistä sinne jore3.md:hen.
</blockquote></details>

I'm sorry, but I'm still missing this kind of sentence from this README:
"For instructions on how to connect to the bastion host, see [Wiki](https://github.com/HSLdevcom/jore4/blob/main/wiki/jore3.md)"


<!-- Sent from Reviewable.io -->

2021-03-10 19:38 UTC, jschummer reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/7)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @pallost)

___
*[README.md, line 171 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/7#-MVLt1Vy8Q1I26mGNCu8:-MVSd6Ii1NOyfqe3p5JJ:b-xi5uef) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/6d5bdd80594e5b04fa5cc5040dcda72d93778937/README.md#L171)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I'm sorry, but I'm still missing this kind of sentence from this README:
"For instructions on how to connect to the bastion host, see [Wiki](https://github.com/HSLdevcom/jore4/blob/main/wiki/jore3.md)"
</blockquote></details>

I now added a link to the proper file in the wiki :+1: 


<!-- Sent from Reviewable.io -->

2021-03-11 08:22 UTC, pallost approved these changes
> Reviewed 1 of 4 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/7)* status: all files reviewed, 2 unresolved discussions (waiting on @jschummer)

___
*[README.md, line 171 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/7#-MVLt1Vy8Q1I26mGNCu8:-MVVN2ZgCUTslYYF5fB3:b-ucfknh) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/6d5bdd80594e5b04fa5cc5040dcda72d93778937/README.md#L171)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

I now added a link to the proper file in the wiki :+1: 
</blockquote></details>

Thanks!


<!-- Sent from Reviewable.io -->

2021-03-11 10:04 UTC, merged